### PR TITLE
Revert to using m-dash in README

### PR DESCRIPTION
**Pull request by Abrifq**
I wonder how many people were confused like me and thought "What is repositories-private", haha

### Why:

Closes: None

### What's being changed:

README.md:L37 The dash dividing cutting the sentence to explain private repositories are using Action Minutes had no spacing, making the `repository-private` seem like a conjuction.
This PR fixes that.

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [X] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by jlaux001 — APPROVED** [review]

**Review by jlaux001 — APPROVED** [review]

**Review by jlaux001 — APPROVED** [review]

**Comment by sinsukehlab** [comment]
I prefer using '&mdash; (`&mdash;`)'.

**Comment by Abrifq** [comment]
> I prefer using '— (`&mdash;`)'.

Following the [Style Guide's Inclusive Language section](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#resources-about-inclusive-language), mdash is not suggested.

> "If you do use a dash, use an en-dash, not a hyphen or an em-dash."
> 
> - [Readibility Guidelines](https://readabilityguidelines.co.uk/grammar-points/hyphens-and-dashes/#6-if-you-do-use-a-dash-use-an-en-dash-not-a-hyphen-or-an-em-dash)

**Comment by Abrifq** [comment]
Also a previous issue (#7) had changed em dash to en dash, it'd be the best to not reintroduce a bug.

**Comment by sinsukehlab** [comment]
> Also a previous issue (#7) had changed em dash to en dash, it'd be the best to not reintroduce a bug.

Previously, this course taught the learners to make a workflow that checked emoji shortcodes.
#7 is now an obsolete issue.

**Comment by Abrifq** [comment]
I see, give me a moment.

**Review by sinsukehlab — APPROVED** [review]

**Comment by sinsukehlab** [comment]
After generating a repository from an older version of the template and checking it, I found that emoji.yml could work well (no false positive) with the character entity reference.

**Review by heiskr — APPROVED** [review]

**Pull request merged**
