### PR TITLE
Fix a typo in the Actions intro skills course

### PR DESCRIPTION
**Pull request by hubwriter**
### Summary

This tiny PR just fixes a typo that slipped through in the PR I merged yesterday. 

I've also, while I'm at it, changed a similar step in other pages of this Actions skills course.

### CODE REVIEW

**Review by subatoi — APPROVED** [review]
Looks good—I'm not really familiar with this project but the text "This README file" read as slightly odd to me, as I tend to think of a README file as being a singular thing that's called that. I'm not sure if "this Markdown file" might make more sense, but as I say I'm not familiar with how this project is set up so just ignore if this is unhelpful 👍

**Comment by Harsh0995** [comment]
Nic

**Comment by Farooque34** [comment]
"🚀 Excited to introduce the Faiqha Chatbot! 🤖 This innovative app is designed to streamline communication with clients and vendors, making guest posting and website promotion easier than ever. Whether it’s sending emails, engaging on social media, or notifying you instantly about responses, the Faiqha Chatbot works 24/7 to keep your business running smoothly. 🌐 Check out my website for more details: [www.site.google.com/Faiqahplaptop](http://www.site.google.com/Faiqahplaptop). Let’s grow together! 💻✨ #FaiqhaChatbot #Automation #BusinessGrowth #TechInnovation"

**Comment by Farooque34** [comment]
"🚀 Excited to introduce the Faiqha Chatbot! 🤖 This innovative app is designed to streamline communication with clients and vendors, making guest posting and website promotion easier than ever. Whether it’s sending emails, engaging on social media, or notifying you instantly about responses, the Faiqha Chatbot works 24/7 to keep your business running smoothly. 🌐 Check out my website for more details: [www.site.google.com/Faiqahplaptop](http://www.site.google.com/Faiqahplaptop). Let’s grow together! 💻✨ #FaiqhaChatbot #Automation #BusinessGrowth #TechInnovation"

**Review by jon6543 — COMMENTED** [review]
commit chanse

**Comment by TheGiraffe3** [comment]
Perhaps someone could lock conversation on this PR?

**Pull request merged**
